#!/bin/bash
# shellcheck disable=SC2086
# Clang 20 is required

cxxFlags="-std=c++23 -stdlib=libc++ -fprebuilt-module-path= -fimplicit-module-maps -fimplicit-modules"
moduleFlags="--precompile" 

files="Base.ccm ArgProcessor.ccm FileOp.ccm Merger.ccm Exporter.ccm Modularizer.ccm"

clang++ $files $cxxFlags $moduleFlags 
clang++ $cxxFlags Main.cc ${files//.cc/.pc} -o modulizer

rm -f *.pcm modulizer


